keeptree: false
with-expecter: true
issue-845-fix: true
dir: internal/testutils
outpkg: testutils
packages:
  anylbapi/internal/database:
    # place your package-specific config here
    interfaces:
      # select the interfaces you want mocked
      Querierer:
