// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForCreateLeaderboardExternalLink implements pgx.CopyFromSource.
type iteratorForCreateLeaderboardExternalLink struct {
	rows                 []CreateLeaderboardExternalLinkParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLeaderboardExternalLink) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLeaderboardExternalLink) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LeaderboardID,
		r.rows[0].DisplayValue,
		r.rows[0].Url,
	}, nil
}

func (r iteratorForCreateLeaderboardExternalLink) Err() error {
	return nil
}

func (q *Queries) CreateLeaderboardExternalLink(ctx context.Context, arg []CreateLeaderboardExternalLinkParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"leaderboard_external_links"}, []string{"leaderboard_id", "display_value", "url"}, &iteratorForCreateLeaderboardExternalLink{rows: arg})
}

// iteratorForCreateLeaderboardFields implements pgx.CopyFromSource.
type iteratorForCreateLeaderboardFields struct {
	rows                 []CreateLeaderboardFieldsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLeaderboardFields) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLeaderboardFields) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Lid,
		r.rows[0].FieldName,
		r.rows[0].FieldValue,
		r.rows[0].FieldOrder,
		r.rows[0].ForRank,
		r.rows[0].Required,
		r.rows[0].Hidden,
	}, nil
}

func (r iteratorForCreateLeaderboardFields) Err() error {
	return nil
}

func (q *Queries) CreateLeaderboardFields(ctx context.Context, arg []CreateLeaderboardFieldsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"leaderboard_fields"}, []string{"lid", "field_name", "field_value", "field_order", "for_rank", "required", "hidden"}, &iteratorForCreateLeaderboardFields{rows: arg})
}

// iteratorForCreateLeaderboardOptions implements pgx.CopyFromSource.
type iteratorForCreateLeaderboardOptions struct {
	rows                 []CreateLeaderboardOptionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLeaderboardOptions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLeaderboardOptions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Fid,
		r.rows[0].Option,
	}, nil
}

func (r iteratorForCreateLeaderboardOptions) Err() error {
	return nil
}

func (q *Queries) CreateLeaderboardOptions(ctx context.Context, arg []CreateLeaderboardOptionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"leaderboard_options"}, []string{"fid", "option"}, &iteratorForCreateLeaderboardOptions{rows: arg})
}
