// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: leaderboard_external_links.sql

package database

type CreateLeaderboardExternalLinkParams struct {
	LeaderboardID int32
	DisplayValue  string
	Url           string
}
