// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: leaderboard_options.sql

package database

import (
	"context"
)

type CreateLeadeboardOptionsParams struct {
	Lid       int32
	FieldName string
	Option    string
}

const getFieldOptions = `-- name: GetFieldOptions :many
SELECT option
FROM leaderboard_options
WHERE lid = $1
    AND field_name = $2
`

type GetFieldOptionsParams struct {
	Lid       int32
	FieldName string
}

func (q *Queries) GetFieldOptions(ctx context.Context, arg GetFieldOptionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getFieldOptions, arg.Lid, arg.FieldName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var option string
		if err := rows.Scan(&option); err != nil {
			return nil, err
		}
		items = append(items, option)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
