// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type FieldType string

const (
	FieldTypeTEXT      FieldType = "TEXT"
	FieldTypeSHORTTEXT FieldType = "SHORT_TEXT"
	FieldTypeINTEGER   FieldType = "INTEGER"
	FieldTypeREAL      FieldType = "REAL"
	FieldTypeDURATION  FieldType = "DURATION"
	FieldTypeTIMESTAMP FieldType = "TIMESTAMP"
	FieldTypeOPTION    FieldType = "OPTION"
)

func (e *FieldType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FieldType(s)
	case string:
		*e = FieldType(s)
	default:
		return fmt.Errorf("unsupported scan type for FieldType: %T", src)
	}
	return nil
}

type NullFieldType struct {
	FieldType FieldType
	Valid     bool // Valid is true if FieldType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFieldType) Scan(value interface{}) error {
	if value == nil {
		ns.FieldType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FieldType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFieldType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FieldType), nil
}

type Leaderboard struct {
	ID                  int32
	Name                string
	Description         sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
	CoverImageUrl       sql.NullString
	AllowAnnonymous     sql.NullBool
	RequireVerification sql.NullBool
	Creator             int32
}

type LeaderboardField struct {
	Lid        int32
	FieldName  string
	FieldValue FieldType
	FieldOrder int32
}

type LeaderboardOption struct {
	Lid       int32
	FieldName string
	Option    string
}

type RefreshToken struct {
	ID              int32
	UserID          int32
	RotationCounter int32
	IssuedAt        time.Time
	ExpiresAt       time.Time
	DeviceInfo      sql.NullString
	IpAddress       sql.NullString
	RevokedAt       sql.NullTime
}

type User struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Username    string
	DisplayName string
	Email       string
	Password    string
	Description sql.NullString
}
