// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	AddFieldToEntriesByLeaderboardId(ctx context.Context, arg AddFieldToEntriesByLeaderboardIdParams) error
	AddLeaderboardOption(ctx context.Context, arg AddLeaderboardOptionParams) error
	AddVerifier(ctx context.Context, arg AddVerifierParams) error
	CreateLeadeboardEntry(ctx context.Context, arg CreateLeadeboardEntryParams) (LeaderboardEntry, error)
	CreateLeadeboardField(ctx context.Context, arg CreateLeadeboardFieldParams) error
	CreateLeadeboardFields(ctx context.Context, arg []CreateLeadeboardFieldsParams) (int64, error)
	CreateLeadeboardOptions(ctx context.Context, arg []CreateLeadeboardOptionsParams) (int64, error)
	CreateLeaderboard(ctx context.Context, arg CreateLeaderboardParams) (Leaderboard, error)
	CreateLeaderboardExternalLink(ctx context.Context, arg []CreateLeaderboardExternalLinkParams) (int64, error)
	CreateNewRefreshToken(ctx context.Context, arg CreateNewRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteEntry(ctx context.Context, id int32) error
	DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) error
	DeleteField(ctx context.Context, arg DeleteFieldParams) error
	DeleteFieldOnEntriesByLeaderboardId(ctx context.Context, arg DeleteFieldOnEntriesByLeaderboardIdParams) error
	DeleteLeadeboardOption(ctx context.Context, arg DeleteLeadeboardOptionParams) error
	DeleteLeadeboardOptions(ctx context.Context, arg DeleteLeadeboardOptionsParams) error
	DeleteLeaderboard(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	DeleteUserByUsername(ctx context.Context, username string) error
	DeleteUserFavorite(ctx context.Context, userID int32) error
	GetFavoriteLeaderboards(ctx context.Context, arg GetFavoriteLeaderboardsParams) ([]GetFavoriteLeaderboardsRow, error)
	GetFieldByLID(ctx context.Context, arg GetFieldByLIDParams) (LeaderboardField, error)
	GetFieldOptions(ctx context.Context, arg GetFieldOptionsParams) ([]string, error)
	GetLeaderboardById(ctx context.Context, id int32) (Leaderboard, error)
	GetLeaderboardEntryById(ctx context.Context, id int32) (LeaderboardEntry, error)
	GetLeaderboardFieldsByLID(ctx context.Context, lid int32) ([]LeaderboardField, error)
	GetLeaderboardFull(ctx context.Context, id int32) ([]GetLeaderboardFullRow, error)
	GetRecentLeaderboards(ctx context.Context, arg GetRecentLeaderboardsParams) ([]GetRecentLeaderboardsRow, error)
	GetRefreshToken(ctx context.Context, id int32) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserFavorite(ctx context.Context, userID int32) ([]LeaderboardFavourite, error)
	GetUsernameFromId(ctx context.Context, id int32) (string, error)
	GetVerifiers(ctx context.Context, leaderboardID int32) ([]User, error)
	RemoveVerifier(ctx context.Context, arg RemoveVerifierParams) error
	RenameFieldOnEntriesByLeaderboardId(ctx context.Context, arg RenameFieldOnEntriesByLeaderboardIdParams) error
	RenameLeadeboardOption(ctx context.Context, arg RenameLeadeboardOptionParams) error
	RevokedAllRefreshToken(ctx context.Context, userID int32) error
	RevokedRefreshToken(ctx context.Context, id int32) error
	UpdateFieldsName(ctx context.Context, arg UpdateFieldsNameParams) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (RefreshToken, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	VerifyEntry(ctx context.Context, arg VerifyEntryParams) error
}

var _ Querier = (*Queries)(nil)
