// Code generated by mockery v2.50.1. DO NOT EDIT.

package testutils

import (
	database "anylbapi/internal/database"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQuerierer is an autogenerated mock type for the Querierer type
type MockQuerierer struct {
	mock.Mock
}

type MockQuerierer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerierer) EXPECT() *MockQuerierer_Expecter {
	return &MockQuerierer_Expecter{mock: &_m.Mock}
}

// AddVerifier provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) AddVerifier(ctx context.Context, arg database.AddVerifierParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddVerifier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.AddVerifierParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_AddVerifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddVerifier'
type MockQuerierer_AddVerifier_Call struct {
	*mock.Call
}

// AddVerifier is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.AddVerifierParams
func (_e *MockQuerierer_Expecter) AddVerifier(ctx interface{}, arg interface{}) *MockQuerierer_AddVerifier_Call {
	return &MockQuerierer_AddVerifier_Call{Call: _e.mock.On("AddVerifier", ctx, arg)}
}

func (_c *MockQuerierer_AddVerifier_Call) Run(run func(ctx context.Context, arg database.AddVerifierParams)) *MockQuerierer_AddVerifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.AddVerifierParams))
	})
	return _c
}

func (_c *MockQuerierer_AddVerifier_Call) Return(_a0 error) *MockQuerierer_AddVerifier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_AddVerifier_Call) RunAndReturn(run func(context.Context, database.AddVerifierParams) error) *MockQuerierer_AddVerifier_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function with given fields: ctx
func (_m *MockQuerierer) BeginTx(ctx context.Context) (database.Querierer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 database.Querierer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (database.Querierer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) database.Querierer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.Querierer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockQuerierer_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerierer_Expecter) BeginTx(ctx interface{}) *MockQuerierer_BeginTx_Call {
	return &MockQuerierer_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockQuerierer_BeginTx_Call) Run(run func(ctx context.Context)) *MockQuerierer_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerierer_BeginTx_Call) Return(_a0 database.Querierer, _a1 error) *MockQuerierer_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_BeginTx_Call) RunAndReturn(run func(context.Context) (database.Querierer, error)) *MockQuerierer_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: ctx
func (_m *MockQuerierer) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockQuerierer_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerierer_Expecter) Commit(ctx interface{}) *MockQuerierer_Commit_Call {
	return &MockQuerierer_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockQuerierer_Commit_Call) Run(run func(ctx context.Context)) *MockQuerierer_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerierer_Commit_Call) Return(_a0 error) *MockQuerierer_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_Commit_Call) RunAndReturn(run func(context.Context) error) *MockQuerierer_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLeadeboardEntry provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) CreateLeadeboardEntry(ctx context.Context, arg database.CreateLeadeboardEntryParams) (database.LeaderboardEntry, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateLeadeboardEntry")
	}

	var r0 database.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateLeadeboardEntryParams) (database.LeaderboardEntry, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateLeadeboardEntryParams) database.LeaderboardEntry); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.LeaderboardEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateLeadeboardEntryParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_CreateLeadeboardEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLeadeboardEntry'
type MockQuerierer_CreateLeadeboardEntry_Call struct {
	*mock.Call
}

// CreateLeadeboardEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.CreateLeadeboardEntryParams
func (_e *MockQuerierer_Expecter) CreateLeadeboardEntry(ctx interface{}, arg interface{}) *MockQuerierer_CreateLeadeboardEntry_Call {
	return &MockQuerierer_CreateLeadeboardEntry_Call{Call: _e.mock.On("CreateLeadeboardEntry", ctx, arg)}
}

func (_c *MockQuerierer_CreateLeadeboardEntry_Call) Run(run func(ctx context.Context, arg database.CreateLeadeboardEntryParams)) *MockQuerierer_CreateLeadeboardEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.CreateLeadeboardEntryParams))
	})
	return _c
}

func (_c *MockQuerierer_CreateLeadeboardEntry_Call) Return(_a0 database.LeaderboardEntry, _a1 error) *MockQuerierer_CreateLeadeboardEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_CreateLeadeboardEntry_Call) RunAndReturn(run func(context.Context, database.CreateLeadeboardEntryParams) (database.LeaderboardEntry, error)) *MockQuerierer_CreateLeadeboardEntry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLeadeboardFields provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) CreateLeadeboardFields(ctx context.Context, arg []database.CreateLeadeboardFieldsParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateLeadeboardFields")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []database.CreateLeadeboardFieldsParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []database.CreateLeadeboardFieldsParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []database.CreateLeadeboardFieldsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_CreateLeadeboardFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLeadeboardFields'
type MockQuerierer_CreateLeadeboardFields_Call struct {
	*mock.Call
}

// CreateLeadeboardFields is a helper method to define mock.On call
//   - ctx context.Context
//   - arg []database.CreateLeadeboardFieldsParams
func (_e *MockQuerierer_Expecter) CreateLeadeboardFields(ctx interface{}, arg interface{}) *MockQuerierer_CreateLeadeboardFields_Call {
	return &MockQuerierer_CreateLeadeboardFields_Call{Call: _e.mock.On("CreateLeadeboardFields", ctx, arg)}
}

func (_c *MockQuerierer_CreateLeadeboardFields_Call) Run(run func(ctx context.Context, arg []database.CreateLeadeboardFieldsParams)) *MockQuerierer_CreateLeadeboardFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]database.CreateLeadeboardFieldsParams))
	})
	return _c
}

func (_c *MockQuerierer_CreateLeadeboardFields_Call) Return(_a0 int64, _a1 error) *MockQuerierer_CreateLeadeboardFields_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_CreateLeadeboardFields_Call) RunAndReturn(run func(context.Context, []database.CreateLeadeboardFieldsParams) (int64, error)) *MockQuerierer_CreateLeadeboardFields_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLeadeboardOptions provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) CreateLeadeboardOptions(ctx context.Context, arg []database.CreateLeadeboardOptionsParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateLeadeboardOptions")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []database.CreateLeadeboardOptionsParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []database.CreateLeadeboardOptionsParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []database.CreateLeadeboardOptionsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_CreateLeadeboardOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLeadeboardOptions'
type MockQuerierer_CreateLeadeboardOptions_Call struct {
	*mock.Call
}

// CreateLeadeboardOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - arg []database.CreateLeadeboardOptionsParams
func (_e *MockQuerierer_Expecter) CreateLeadeboardOptions(ctx interface{}, arg interface{}) *MockQuerierer_CreateLeadeboardOptions_Call {
	return &MockQuerierer_CreateLeadeboardOptions_Call{Call: _e.mock.On("CreateLeadeboardOptions", ctx, arg)}
}

func (_c *MockQuerierer_CreateLeadeboardOptions_Call) Run(run func(ctx context.Context, arg []database.CreateLeadeboardOptionsParams)) *MockQuerierer_CreateLeadeboardOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]database.CreateLeadeboardOptionsParams))
	})
	return _c
}

func (_c *MockQuerierer_CreateLeadeboardOptions_Call) Return(_a0 int64, _a1 error) *MockQuerierer_CreateLeadeboardOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_CreateLeadeboardOptions_Call) RunAndReturn(run func(context.Context, []database.CreateLeadeboardOptionsParams) (int64, error)) *MockQuerierer_CreateLeadeboardOptions_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLeaderboard provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) CreateLeaderboard(ctx context.Context, arg database.CreateLeaderboardParams) (database.Leaderboard, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateLeaderboard")
	}

	var r0 database.Leaderboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateLeaderboardParams) (database.Leaderboard, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateLeaderboardParams) database.Leaderboard); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.Leaderboard)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateLeaderboardParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_CreateLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLeaderboard'
type MockQuerierer_CreateLeaderboard_Call struct {
	*mock.Call
}

// CreateLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.CreateLeaderboardParams
func (_e *MockQuerierer_Expecter) CreateLeaderboard(ctx interface{}, arg interface{}) *MockQuerierer_CreateLeaderboard_Call {
	return &MockQuerierer_CreateLeaderboard_Call{Call: _e.mock.On("CreateLeaderboard", ctx, arg)}
}

func (_c *MockQuerierer_CreateLeaderboard_Call) Run(run func(ctx context.Context, arg database.CreateLeaderboardParams)) *MockQuerierer_CreateLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.CreateLeaderboardParams))
	})
	return _c
}

func (_c *MockQuerierer_CreateLeaderboard_Call) Return(_a0 database.Leaderboard, _a1 error) *MockQuerierer_CreateLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_CreateLeaderboard_Call) RunAndReturn(run func(context.Context, database.CreateLeaderboardParams) (database.Leaderboard, error)) *MockQuerierer_CreateLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLeaderboardExternalLink provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) CreateLeaderboardExternalLink(ctx context.Context, arg []database.CreateLeaderboardExternalLinkParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateLeaderboardExternalLink")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []database.CreateLeaderboardExternalLinkParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []database.CreateLeaderboardExternalLinkParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []database.CreateLeaderboardExternalLinkParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_CreateLeaderboardExternalLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLeaderboardExternalLink'
type MockQuerierer_CreateLeaderboardExternalLink_Call struct {
	*mock.Call
}

// CreateLeaderboardExternalLink is a helper method to define mock.On call
//   - ctx context.Context
//   - arg []database.CreateLeaderboardExternalLinkParams
func (_e *MockQuerierer_Expecter) CreateLeaderboardExternalLink(ctx interface{}, arg interface{}) *MockQuerierer_CreateLeaderboardExternalLink_Call {
	return &MockQuerierer_CreateLeaderboardExternalLink_Call{Call: _e.mock.On("CreateLeaderboardExternalLink", ctx, arg)}
}

func (_c *MockQuerierer_CreateLeaderboardExternalLink_Call) Run(run func(ctx context.Context, arg []database.CreateLeaderboardExternalLinkParams)) *MockQuerierer_CreateLeaderboardExternalLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]database.CreateLeaderboardExternalLinkParams))
	})
	return _c
}

func (_c *MockQuerierer_CreateLeaderboardExternalLink_Call) Return(_a0 int64, _a1 error) *MockQuerierer_CreateLeaderboardExternalLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_CreateLeaderboardExternalLink_Call) RunAndReturn(run func(context.Context, []database.CreateLeaderboardExternalLinkParams) (int64, error)) *MockQuerierer_CreateLeaderboardExternalLink_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNewRefreshToken provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) CreateNewRefreshToken(ctx context.Context, arg database.CreateNewRefreshTokenParams) (database.RefreshToken, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewRefreshToken")
	}

	var r0 database.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateNewRefreshTokenParams) (database.RefreshToken, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateNewRefreshTokenParams) database.RefreshToken); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateNewRefreshTokenParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_CreateNewRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewRefreshToken'
type MockQuerierer_CreateNewRefreshToken_Call struct {
	*mock.Call
}

// CreateNewRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.CreateNewRefreshTokenParams
func (_e *MockQuerierer_Expecter) CreateNewRefreshToken(ctx interface{}, arg interface{}) *MockQuerierer_CreateNewRefreshToken_Call {
	return &MockQuerierer_CreateNewRefreshToken_Call{Call: _e.mock.On("CreateNewRefreshToken", ctx, arg)}
}

func (_c *MockQuerierer_CreateNewRefreshToken_Call) Run(run func(ctx context.Context, arg database.CreateNewRefreshTokenParams)) *MockQuerierer_CreateNewRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.CreateNewRefreshTokenParams))
	})
	return _c
}

func (_c *MockQuerierer_CreateNewRefreshToken_Call) Return(_a0 database.RefreshToken, _a1 error) *MockQuerierer_CreateNewRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_CreateNewRefreshToken_Call) RunAndReturn(run func(context.Context, database.CreateNewRefreshTokenParams) (database.RefreshToken, error)) *MockQuerierer_CreateNewRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) CreateUser(ctx context.Context, arg database.CreateUserParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateUserParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerierer_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.CreateUserParams
func (_e *MockQuerierer_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockQuerierer_CreateUser_Call {
	return &MockQuerierer_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerierer_CreateUser_Call) Run(run func(ctx context.Context, arg database.CreateUserParams)) *MockQuerierer_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.CreateUserParams))
	})
	return _c
}

func (_c *MockQuerierer_CreateUser_Call) Return(_a0 error) *MockQuerierer_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_CreateUser_Call) RunAndReturn(run func(context.Context, database.CreateUserParams) error) *MockQuerierer_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntry provides a mock function with given fields: ctx, id
func (_m *MockQuerierer) DeleteEntry(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_DeleteEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntry'
type MockQuerierer_DeleteEntry_Call struct {
	*mock.Call
}

// DeleteEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerierer_Expecter) DeleteEntry(ctx interface{}, id interface{}) *MockQuerierer_DeleteEntry_Call {
	return &MockQuerierer_DeleteEntry_Call{Call: _e.mock.On("DeleteEntry", ctx, id)}
}

func (_c *MockQuerierer_DeleteEntry_Call) Run(run func(ctx context.Context, id int32)) *MockQuerierer_DeleteEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_DeleteEntry_Call) Return(_a0 error) *MockQuerierer_DeleteEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_DeleteEntry_Call) RunAndReturn(run func(context.Context, int32) error) *MockQuerierer_DeleteEntry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLeaderboard provides a mock function with given fields: ctx, id
func (_m *MockQuerierer) DeleteLeaderboard(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLeaderboard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_DeleteLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLeaderboard'
type MockQuerierer_DeleteLeaderboard_Call struct {
	*mock.Call
}

// DeleteLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerierer_Expecter) DeleteLeaderboard(ctx interface{}, id interface{}) *MockQuerierer_DeleteLeaderboard_Call {
	return &MockQuerierer_DeleteLeaderboard_Call{Call: _e.mock.On("DeleteLeaderboard", ctx, id)}
}

func (_c *MockQuerierer_DeleteLeaderboard_Call) Run(run func(ctx context.Context, id int32)) *MockQuerierer_DeleteLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_DeleteLeaderboard_Call) Return(_a0 error) *MockQuerierer_DeleteLeaderboard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_DeleteLeaderboard_Call) RunAndReturn(run func(context.Context, int32) error) *MockQuerierer_DeleteLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *MockQuerierer) DeleteUser(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockQuerierer_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerierer_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockQuerierer_DeleteUser_Call {
	return &MockQuerierer_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockQuerierer_DeleteUser_Call) Run(run func(ctx context.Context, id int32)) *MockQuerierer_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_DeleteUser_Call) Return(_a0 error) *MockQuerierer_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_DeleteUser_Call) RunAndReturn(run func(context.Context, int32) error) *MockQuerierer_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserByUsername provides a mock function with given fields: ctx, username
func (_m *MockQuerierer) DeleteUserByUsername(ctx context.Context, username string) error {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByUsername")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_DeleteUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByUsername'
type MockQuerierer_DeleteUserByUsername_Call struct {
	*mock.Call
}

// DeleteUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockQuerierer_Expecter) DeleteUserByUsername(ctx interface{}, username interface{}) *MockQuerierer_DeleteUserByUsername_Call {
	return &MockQuerierer_DeleteUserByUsername_Call{Call: _e.mock.On("DeleteUserByUsername", ctx, username)}
}

func (_c *MockQuerierer_DeleteUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockQuerierer_DeleteUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerierer_DeleteUserByUsername_Call) Return(_a0 error) *MockQuerierer_DeleteUserByUsername_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_DeleteUserByUsername_Call) RunAndReturn(run func(context.Context, string) error) *MockQuerierer_DeleteUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntriesFromLeaderboardId provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) GetEntriesFromLeaderboardId(ctx context.Context, arg database.GetEntriesFromLeaderboardIdParams) ([]database.LeaderboardEntry, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetEntriesFromLeaderboardId")
	}

	var r0 []database.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetEntriesFromLeaderboardIdParams) ([]database.LeaderboardEntry, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetEntriesFromLeaderboardIdParams) []database.LeaderboardEntry); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetEntriesFromLeaderboardIdParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetEntriesFromLeaderboardId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntriesFromLeaderboardId'
type MockQuerierer_GetEntriesFromLeaderboardId_Call struct {
	*mock.Call
}

// GetEntriesFromLeaderboardId is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.GetEntriesFromLeaderboardIdParams
func (_e *MockQuerierer_Expecter) GetEntriesFromLeaderboardId(ctx interface{}, arg interface{}) *MockQuerierer_GetEntriesFromLeaderboardId_Call {
	return &MockQuerierer_GetEntriesFromLeaderboardId_Call{Call: _e.mock.On("GetEntriesFromLeaderboardId", ctx, arg)}
}

func (_c *MockQuerierer_GetEntriesFromLeaderboardId_Call) Run(run func(ctx context.Context, arg database.GetEntriesFromLeaderboardIdParams)) *MockQuerierer_GetEntriesFromLeaderboardId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.GetEntriesFromLeaderboardIdParams))
	})
	return _c
}

func (_c *MockQuerierer_GetEntriesFromLeaderboardId_Call) Return(_a0 []database.LeaderboardEntry, _a1 error) *MockQuerierer_GetEntriesFromLeaderboardId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetEntriesFromLeaderboardId_Call) RunAndReturn(run func(context.Context, database.GetEntriesFromLeaderboardIdParams) ([]database.LeaderboardEntry, error)) *MockQuerierer_GetEntriesFromLeaderboardId_Call {
	_c.Call.Return(run)
	return _c
}

// GetFieldOptions provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) GetFieldOptions(ctx context.Context, arg database.GetFieldOptionsParams) ([]string, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetFieldOptions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetFieldOptionsParams) ([]string, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetFieldOptionsParams) []string); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetFieldOptionsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetFieldOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFieldOptions'
type MockQuerierer_GetFieldOptions_Call struct {
	*mock.Call
}

// GetFieldOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.GetFieldOptionsParams
func (_e *MockQuerierer_Expecter) GetFieldOptions(ctx interface{}, arg interface{}) *MockQuerierer_GetFieldOptions_Call {
	return &MockQuerierer_GetFieldOptions_Call{Call: _e.mock.On("GetFieldOptions", ctx, arg)}
}

func (_c *MockQuerierer_GetFieldOptions_Call) Run(run func(ctx context.Context, arg database.GetFieldOptionsParams)) *MockQuerierer_GetFieldOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.GetFieldOptionsParams))
	})
	return _c
}

func (_c *MockQuerierer_GetFieldOptions_Call) Return(_a0 []string, _a1 error) *MockQuerierer_GetFieldOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetFieldOptions_Call) RunAndReturn(run func(context.Context, database.GetFieldOptionsParams) ([]string, error)) *MockQuerierer_GetFieldOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaderboardById provides a mock function with given fields: ctx, id
func (_m *MockQuerierer) GetLeaderboardById(ctx context.Context, id int32) (database.Leaderboard, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboardById")
	}

	var r0 database.Leaderboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (database.Leaderboard, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) database.Leaderboard); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.Leaderboard)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetLeaderboardById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboardById'
type MockQuerierer_GetLeaderboardById_Call struct {
	*mock.Call
}

// GetLeaderboardById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerierer_Expecter) GetLeaderboardById(ctx interface{}, id interface{}) *MockQuerierer_GetLeaderboardById_Call {
	return &MockQuerierer_GetLeaderboardById_Call{Call: _e.mock.On("GetLeaderboardById", ctx, id)}
}

func (_c *MockQuerierer_GetLeaderboardById_Call) Run(run func(ctx context.Context, id int32)) *MockQuerierer_GetLeaderboardById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_GetLeaderboardById_Call) Return(_a0 database.Leaderboard, _a1 error) *MockQuerierer_GetLeaderboardById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetLeaderboardById_Call) RunAndReturn(run func(context.Context, int32) (database.Leaderboard, error)) *MockQuerierer_GetLeaderboardById_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaderboardEntriesCount provides a mock function with given fields: ctx, leaderboardID
func (_m *MockQuerierer) GetLeaderboardEntriesCount(ctx context.Context, leaderboardID int32) (int64, error) {
	ret := _m.Called(ctx, leaderboardID)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboardEntriesCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (int64, error)); ok {
		return rf(ctx, leaderboardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) int64); ok {
		r0 = rf(ctx, leaderboardID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, leaderboardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetLeaderboardEntriesCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboardEntriesCount'
type MockQuerierer_GetLeaderboardEntriesCount_Call struct {
	*mock.Call
}

// GetLeaderboardEntriesCount is a helper method to define mock.On call
//   - ctx context.Context
//   - leaderboardID int32
func (_e *MockQuerierer_Expecter) GetLeaderboardEntriesCount(ctx interface{}, leaderboardID interface{}) *MockQuerierer_GetLeaderboardEntriesCount_Call {
	return &MockQuerierer_GetLeaderboardEntriesCount_Call{Call: _e.mock.On("GetLeaderboardEntriesCount", ctx, leaderboardID)}
}

func (_c *MockQuerierer_GetLeaderboardEntriesCount_Call) Run(run func(ctx context.Context, leaderboardID int32)) *MockQuerierer_GetLeaderboardEntriesCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_GetLeaderboardEntriesCount_Call) Return(_a0 int64, _a1 error) *MockQuerierer_GetLeaderboardEntriesCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetLeaderboardEntriesCount_Call) RunAndReturn(run func(context.Context, int32) (int64, error)) *MockQuerierer_GetLeaderboardEntriesCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaderboardEntryById provides a mock function with given fields: ctx, id
func (_m *MockQuerierer) GetLeaderboardEntryById(ctx context.Context, id int32) (database.LeaderboardEntry, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboardEntryById")
	}

	var r0 database.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (database.LeaderboardEntry, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) database.LeaderboardEntry); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.LeaderboardEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetLeaderboardEntryById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboardEntryById'
type MockQuerierer_GetLeaderboardEntryById_Call struct {
	*mock.Call
}

// GetLeaderboardEntryById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerierer_Expecter) GetLeaderboardEntryById(ctx interface{}, id interface{}) *MockQuerierer_GetLeaderboardEntryById_Call {
	return &MockQuerierer_GetLeaderboardEntryById_Call{Call: _e.mock.On("GetLeaderboardEntryById", ctx, id)}
}

func (_c *MockQuerierer_GetLeaderboardEntryById_Call) Run(run func(ctx context.Context, id int32)) *MockQuerierer_GetLeaderboardEntryById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_GetLeaderboardEntryById_Call) Return(_a0 database.LeaderboardEntry, _a1 error) *MockQuerierer_GetLeaderboardEntryById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetLeaderboardEntryById_Call) RunAndReturn(run func(context.Context, int32) (database.LeaderboardEntry, error)) *MockQuerierer_GetLeaderboardEntryById_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaderboardFieldsByLID provides a mock function with given fields: ctx, lid
func (_m *MockQuerierer) GetLeaderboardFieldsByLID(ctx context.Context, lid int32) ([]database.LeaderboardField, error) {
	ret := _m.Called(ctx, lid)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboardFieldsByLID")
	}

	var r0 []database.LeaderboardField
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]database.LeaderboardField, error)); ok {
		return rf(ctx, lid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []database.LeaderboardField); ok {
		r0 = rf(ctx, lid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.LeaderboardField)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, lid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetLeaderboardFieldsByLID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboardFieldsByLID'
type MockQuerierer_GetLeaderboardFieldsByLID_Call struct {
	*mock.Call
}

// GetLeaderboardFieldsByLID is a helper method to define mock.On call
//   - ctx context.Context
//   - lid int32
func (_e *MockQuerierer_Expecter) GetLeaderboardFieldsByLID(ctx interface{}, lid interface{}) *MockQuerierer_GetLeaderboardFieldsByLID_Call {
	return &MockQuerierer_GetLeaderboardFieldsByLID_Call{Call: _e.mock.On("GetLeaderboardFieldsByLID", ctx, lid)}
}

func (_c *MockQuerierer_GetLeaderboardFieldsByLID_Call) Run(run func(ctx context.Context, lid int32)) *MockQuerierer_GetLeaderboardFieldsByLID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_GetLeaderboardFieldsByLID_Call) Return(_a0 []database.LeaderboardField, _a1 error) *MockQuerierer_GetLeaderboardFieldsByLID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetLeaderboardFieldsByLID_Call) RunAndReturn(run func(context.Context, int32) ([]database.LeaderboardField, error)) *MockQuerierer_GetLeaderboardFieldsByLID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaderboardFull provides a mock function with given fields: ctx, id
func (_m *MockQuerierer) GetLeaderboardFull(ctx context.Context, id int32) ([]database.GetLeaderboardFullRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboardFull")
	}

	var r0 []database.GetLeaderboardFullRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]database.GetLeaderboardFullRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []database.GetLeaderboardFullRow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetLeaderboardFullRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetLeaderboardFull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboardFull'
type MockQuerierer_GetLeaderboardFull_Call struct {
	*mock.Call
}

// GetLeaderboardFull is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerierer_Expecter) GetLeaderboardFull(ctx interface{}, id interface{}) *MockQuerierer_GetLeaderboardFull_Call {
	return &MockQuerierer_GetLeaderboardFull_Call{Call: _e.mock.On("GetLeaderboardFull", ctx, id)}
}

func (_c *MockQuerierer_GetLeaderboardFull_Call) Run(run func(ctx context.Context, id int32)) *MockQuerierer_GetLeaderboardFull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_GetLeaderboardFull_Call) Return(_a0 []database.GetLeaderboardFullRow, _a1 error) *MockQuerierer_GetLeaderboardFull_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetLeaderboardFull_Call) RunAndReturn(run func(context.Context, int32) ([]database.GetLeaderboardFullRow, error)) *MockQuerierer_GetLeaderboardFull_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaderboardVerifiedEntriesCount provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) GetLeaderboardVerifiedEntriesCount(ctx context.Context, arg database.GetLeaderboardVerifiedEntriesCountParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboardVerifiedEntriesCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetLeaderboardVerifiedEntriesCountParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetLeaderboardVerifiedEntriesCountParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetLeaderboardVerifiedEntriesCountParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetLeaderboardVerifiedEntriesCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboardVerifiedEntriesCount'
type MockQuerierer_GetLeaderboardVerifiedEntriesCount_Call struct {
	*mock.Call
}

// GetLeaderboardVerifiedEntriesCount is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.GetLeaderboardVerifiedEntriesCountParams
func (_e *MockQuerierer_Expecter) GetLeaderboardVerifiedEntriesCount(ctx interface{}, arg interface{}) *MockQuerierer_GetLeaderboardVerifiedEntriesCount_Call {
	return &MockQuerierer_GetLeaderboardVerifiedEntriesCount_Call{Call: _e.mock.On("GetLeaderboardVerifiedEntriesCount", ctx, arg)}
}

func (_c *MockQuerierer_GetLeaderboardVerifiedEntriesCount_Call) Run(run func(ctx context.Context, arg database.GetLeaderboardVerifiedEntriesCountParams)) *MockQuerierer_GetLeaderboardVerifiedEntriesCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.GetLeaderboardVerifiedEntriesCountParams))
	})
	return _c
}

func (_c *MockQuerierer_GetLeaderboardVerifiedEntriesCount_Call) Return(_a0 int64, _a1 error) *MockQuerierer_GetLeaderboardVerifiedEntriesCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetLeaderboardVerifiedEntriesCount_Call) RunAndReturn(run func(context.Context, database.GetLeaderboardVerifiedEntriesCountParams) (int64, error)) *MockQuerierer_GetLeaderboardVerifiedEntriesCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingEntriesCount provides a mock function with given fields: ctx, leaderboardID
func (_m *MockQuerierer) GetPendingEntriesCount(ctx context.Context, leaderboardID int32) (int64, error) {
	ret := _m.Called(ctx, leaderboardID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingEntriesCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (int64, error)); ok {
		return rf(ctx, leaderboardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) int64); ok {
		r0 = rf(ctx, leaderboardID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, leaderboardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetPendingEntriesCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingEntriesCount'
type MockQuerierer_GetPendingEntriesCount_Call struct {
	*mock.Call
}

// GetPendingEntriesCount is a helper method to define mock.On call
//   - ctx context.Context
//   - leaderboardID int32
func (_e *MockQuerierer_Expecter) GetPendingEntriesCount(ctx interface{}, leaderboardID interface{}) *MockQuerierer_GetPendingEntriesCount_Call {
	return &MockQuerierer_GetPendingEntriesCount_Call{Call: _e.mock.On("GetPendingEntriesCount", ctx, leaderboardID)}
}

func (_c *MockQuerierer_GetPendingEntriesCount_Call) Run(run func(ctx context.Context, leaderboardID int32)) *MockQuerierer_GetPendingEntriesCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_GetPendingEntriesCount_Call) Return(_a0 int64, _a1 error) *MockQuerierer_GetPendingEntriesCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetPendingEntriesCount_Call) RunAndReturn(run func(context.Context, int32) (int64, error)) *MockQuerierer_GetPendingEntriesCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingVerifiedEntries provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) GetPendingVerifiedEntries(ctx context.Context, arg database.GetPendingVerifiedEntriesParams) ([]database.LeaderboardEntry, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingVerifiedEntries")
	}

	var r0 []database.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetPendingVerifiedEntriesParams) ([]database.LeaderboardEntry, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetPendingVerifiedEntriesParams) []database.LeaderboardEntry); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetPendingVerifiedEntriesParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetPendingVerifiedEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingVerifiedEntries'
type MockQuerierer_GetPendingVerifiedEntries_Call struct {
	*mock.Call
}

// GetPendingVerifiedEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.GetPendingVerifiedEntriesParams
func (_e *MockQuerierer_Expecter) GetPendingVerifiedEntries(ctx interface{}, arg interface{}) *MockQuerierer_GetPendingVerifiedEntries_Call {
	return &MockQuerierer_GetPendingVerifiedEntries_Call{Call: _e.mock.On("GetPendingVerifiedEntries", ctx, arg)}
}

func (_c *MockQuerierer_GetPendingVerifiedEntries_Call) Run(run func(ctx context.Context, arg database.GetPendingVerifiedEntriesParams)) *MockQuerierer_GetPendingVerifiedEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.GetPendingVerifiedEntriesParams))
	})
	return _c
}

func (_c *MockQuerierer_GetPendingVerifiedEntries_Call) Return(_a0 []database.LeaderboardEntry, _a1 error) *MockQuerierer_GetPendingVerifiedEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetPendingVerifiedEntries_Call) RunAndReturn(run func(context.Context, database.GetPendingVerifiedEntriesParams) ([]database.LeaderboardEntry, error)) *MockQuerierer_GetPendingVerifiedEntries_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentLeaderboards provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) GetRecentLeaderboards(ctx context.Context, arg database.GetRecentLeaderboardsParams) ([]database.GetRecentLeaderboardsRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentLeaderboards")
	}

	var r0 []database.GetRecentLeaderboardsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetRecentLeaderboardsParams) ([]database.GetRecentLeaderboardsRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetRecentLeaderboardsParams) []database.GetRecentLeaderboardsRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetRecentLeaderboardsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetRecentLeaderboardsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetRecentLeaderboards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentLeaderboards'
type MockQuerierer_GetRecentLeaderboards_Call struct {
	*mock.Call
}

// GetRecentLeaderboards is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.GetRecentLeaderboardsParams
func (_e *MockQuerierer_Expecter) GetRecentLeaderboards(ctx interface{}, arg interface{}) *MockQuerierer_GetRecentLeaderboards_Call {
	return &MockQuerierer_GetRecentLeaderboards_Call{Call: _e.mock.On("GetRecentLeaderboards", ctx, arg)}
}

func (_c *MockQuerierer_GetRecentLeaderboards_Call) Run(run func(ctx context.Context, arg database.GetRecentLeaderboardsParams)) *MockQuerierer_GetRecentLeaderboards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.GetRecentLeaderboardsParams))
	})
	return _c
}

func (_c *MockQuerierer_GetRecentLeaderboards_Call) Return(_a0 []database.GetRecentLeaderboardsRow, _a1 error) *MockQuerierer_GetRecentLeaderboards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetRecentLeaderboards_Call) RunAndReturn(run func(context.Context, database.GetRecentLeaderboardsParams) ([]database.GetRecentLeaderboardsRow, error)) *MockQuerierer_GetRecentLeaderboards_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function with given fields: ctx, id
func (_m *MockQuerierer) GetRefreshToken(ctx context.Context, id int32) (database.RefreshToken, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 database.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (database.RefreshToken, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) database.RefreshToken); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockQuerierer_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerierer_Expecter) GetRefreshToken(ctx interface{}, id interface{}) *MockQuerierer_GetRefreshToken_Call {
	return &MockQuerierer_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, id)}
}

func (_c *MockQuerierer_GetRefreshToken_Call) Run(run func(ctx context.Context, id int32)) *MockQuerierer_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_GetRefreshToken_Call) Return(_a0 database.RefreshToken, _a1 error) *MockQuerierer_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetRefreshToken_Call) RunAndReturn(run func(context.Context, int32) (database.RefreshToken, error)) *MockQuerierer_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockQuerierer) GetUserByEmail(ctx context.Context, email string) (database.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (database.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) database.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockQuerierer_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockQuerierer_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockQuerierer_GetUserByEmail_Call {
	return &MockQuerierer_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockQuerierer_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockQuerierer_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerierer_GetUserByEmail_Call) Return(_a0 database.User, _a1 error) *MockQuerierer_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (database.User, error)) *MockQuerierer_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockQuerierer) GetUserByID(ctx context.Context, id int32) (database.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (database.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) database.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockQuerierer_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerierer_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockQuerierer_GetUserByID_Call {
	return &MockQuerierer_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockQuerierer_GetUserByID_Call) Run(run func(ctx context.Context, id int32)) *MockQuerierer_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_GetUserByID_Call) Return(_a0 database.User, _a1 error) *MockQuerierer_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetUserByID_Call) RunAndReturn(run func(context.Context, int32) (database.User, error)) *MockQuerierer_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function with given fields: ctx, username
func (_m *MockQuerierer) GetUserByUsername(ctx context.Context, username string) (database.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (database.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) database.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockQuerierer_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockQuerierer_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *MockQuerierer_GetUserByUsername_Call {
	return &MockQuerierer_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockQuerierer_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockQuerierer_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerierer_GetUserByUsername_Call) Return(_a0 database.User, _a1 error) *MockQuerierer_GetUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetUserByUsername_Call) RunAndReturn(run func(context.Context, string) (database.User, error)) *MockQuerierer_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetVerifiedEntriesFromLeaderboardId provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) GetVerifiedEntriesFromLeaderboardId(ctx context.Context, arg database.GetVerifiedEntriesFromLeaderboardIdParams) ([]database.LeaderboardEntry, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetVerifiedEntriesFromLeaderboardId")
	}

	var r0 []database.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetVerifiedEntriesFromLeaderboardIdParams) ([]database.LeaderboardEntry, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetVerifiedEntriesFromLeaderboardIdParams) []database.LeaderboardEntry); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetVerifiedEntriesFromLeaderboardIdParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetVerifiedEntriesFromLeaderboardId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVerifiedEntriesFromLeaderboardId'
type MockQuerierer_GetVerifiedEntriesFromLeaderboardId_Call struct {
	*mock.Call
}

// GetVerifiedEntriesFromLeaderboardId is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.GetVerifiedEntriesFromLeaderboardIdParams
func (_e *MockQuerierer_Expecter) GetVerifiedEntriesFromLeaderboardId(ctx interface{}, arg interface{}) *MockQuerierer_GetVerifiedEntriesFromLeaderboardId_Call {
	return &MockQuerierer_GetVerifiedEntriesFromLeaderboardId_Call{Call: _e.mock.On("GetVerifiedEntriesFromLeaderboardId", ctx, arg)}
}

func (_c *MockQuerierer_GetVerifiedEntriesFromLeaderboardId_Call) Run(run func(ctx context.Context, arg database.GetVerifiedEntriesFromLeaderboardIdParams)) *MockQuerierer_GetVerifiedEntriesFromLeaderboardId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.GetVerifiedEntriesFromLeaderboardIdParams))
	})
	return _c
}

func (_c *MockQuerierer_GetVerifiedEntriesFromLeaderboardId_Call) Return(_a0 []database.LeaderboardEntry, _a1 error) *MockQuerierer_GetVerifiedEntriesFromLeaderboardId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetVerifiedEntriesFromLeaderboardId_Call) RunAndReturn(run func(context.Context, database.GetVerifiedEntriesFromLeaderboardIdParams) ([]database.LeaderboardEntry, error)) *MockQuerierer_GetVerifiedEntriesFromLeaderboardId_Call {
	_c.Call.Return(run)
	return _c
}

// GetVerifiers provides a mock function with given fields: ctx, leaderboardID
func (_m *MockQuerierer) GetVerifiers(ctx context.Context, leaderboardID int32) ([]database.User, error) {
	ret := _m.Called(ctx, leaderboardID)

	if len(ret) == 0 {
		panic("no return value specified for GetVerifiers")
	}

	var r0 []database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]database.User, error)); ok {
		return rf(ctx, leaderboardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []database.User); ok {
		r0 = rf(ctx, leaderboardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, leaderboardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_GetVerifiers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVerifiers'
type MockQuerierer_GetVerifiers_Call struct {
	*mock.Call
}

// GetVerifiers is a helper method to define mock.On call
//   - ctx context.Context
//   - leaderboardID int32
func (_e *MockQuerierer_Expecter) GetVerifiers(ctx interface{}, leaderboardID interface{}) *MockQuerierer_GetVerifiers_Call {
	return &MockQuerierer_GetVerifiers_Call{Call: _e.mock.On("GetVerifiers", ctx, leaderboardID)}
}

func (_c *MockQuerierer_GetVerifiers_Call) Run(run func(ctx context.Context, leaderboardID int32)) *MockQuerierer_GetVerifiers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_GetVerifiers_Call) Return(_a0 []database.User, _a1 error) *MockQuerierer_GetVerifiers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_GetVerifiers_Call) RunAndReturn(run func(context.Context, int32) ([]database.User, error)) *MockQuerierer_GetVerifiers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveVerifier provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) RemoveVerifier(ctx context.Context, arg database.RemoveVerifierParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVerifier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.RemoveVerifierParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_RemoveVerifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveVerifier'
type MockQuerierer_RemoveVerifier_Call struct {
	*mock.Call
}

// RemoveVerifier is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.RemoveVerifierParams
func (_e *MockQuerierer_Expecter) RemoveVerifier(ctx interface{}, arg interface{}) *MockQuerierer_RemoveVerifier_Call {
	return &MockQuerierer_RemoveVerifier_Call{Call: _e.mock.On("RemoveVerifier", ctx, arg)}
}

func (_c *MockQuerierer_RemoveVerifier_Call) Run(run func(ctx context.Context, arg database.RemoveVerifierParams)) *MockQuerierer_RemoveVerifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.RemoveVerifierParams))
	})
	return _c
}

func (_c *MockQuerierer_RemoveVerifier_Call) Return(_a0 error) *MockQuerierer_RemoveVerifier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_RemoveVerifier_Call) RunAndReturn(run func(context.Context, database.RemoveVerifierParams) error) *MockQuerierer_RemoveVerifier_Call {
	_c.Call.Return(run)
	return _c
}

// RevokedAllRefreshToken provides a mock function with given fields: ctx, userID
func (_m *MockQuerierer) RevokedAllRefreshToken(ctx context.Context, userID int32) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokedAllRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_RevokedAllRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokedAllRefreshToken'
type MockQuerierer_RevokedAllRefreshToken_Call struct {
	*mock.Call
}

// RevokedAllRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int32
func (_e *MockQuerierer_Expecter) RevokedAllRefreshToken(ctx interface{}, userID interface{}) *MockQuerierer_RevokedAllRefreshToken_Call {
	return &MockQuerierer_RevokedAllRefreshToken_Call{Call: _e.mock.On("RevokedAllRefreshToken", ctx, userID)}
}

func (_c *MockQuerierer_RevokedAllRefreshToken_Call) Run(run func(ctx context.Context, userID int32)) *MockQuerierer_RevokedAllRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_RevokedAllRefreshToken_Call) Return(_a0 error) *MockQuerierer_RevokedAllRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_RevokedAllRefreshToken_Call) RunAndReturn(run func(context.Context, int32) error) *MockQuerierer_RevokedAllRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokedRefreshToken provides a mock function with given fields: ctx, id
func (_m *MockQuerierer) RevokedRefreshToken(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokedRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_RevokedRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokedRefreshToken'
type MockQuerierer_RevokedRefreshToken_Call struct {
	*mock.Call
}

// RevokedRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerierer_Expecter) RevokedRefreshToken(ctx interface{}, id interface{}) *MockQuerierer_RevokedRefreshToken_Call {
	return &MockQuerierer_RevokedRefreshToken_Call{Call: _e.mock.On("RevokedRefreshToken", ctx, id)}
}

func (_c *MockQuerierer_RevokedRefreshToken_Call) Run(run func(ctx context.Context, id int32)) *MockQuerierer_RevokedRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockQuerierer_RevokedRefreshToken_Call) Return(_a0 error) *MockQuerierer_RevokedRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_RevokedRefreshToken_Call) RunAndReturn(run func(context.Context, int32) error) *MockQuerierer_RevokedRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockQuerierer) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockQuerierer_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerierer_Expecter) Rollback(ctx interface{}) *MockQuerierer_Rollback_Call {
	return &MockQuerierer_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockQuerierer_Rollback_Call) Run(run func(ctx context.Context)) *MockQuerierer_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerierer_Rollback_Call) Return(_a0 error) *MockQuerierer_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockQuerierer_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRefreshToken provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) UpdateRefreshToken(ctx context.Context, arg database.UpdateRefreshTokenParams) (database.RefreshToken, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRefreshToken")
	}

	var r0 database.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateRefreshTokenParams) (database.RefreshToken, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateRefreshTokenParams) database.RefreshToken); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.UpdateRefreshTokenParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerierer_UpdateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRefreshToken'
type MockQuerierer_UpdateRefreshToken_Call struct {
	*mock.Call
}

// UpdateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.UpdateRefreshTokenParams
func (_e *MockQuerierer_Expecter) UpdateRefreshToken(ctx interface{}, arg interface{}) *MockQuerierer_UpdateRefreshToken_Call {
	return &MockQuerierer_UpdateRefreshToken_Call{Call: _e.mock.On("UpdateRefreshToken", ctx, arg)}
}

func (_c *MockQuerierer_UpdateRefreshToken_Call) Run(run func(ctx context.Context, arg database.UpdateRefreshTokenParams)) *MockQuerierer_UpdateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.UpdateRefreshTokenParams))
	})
	return _c
}

func (_c *MockQuerierer_UpdateRefreshToken_Call) Return(_a0 database.RefreshToken, _a1 error) *MockQuerierer_UpdateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerierer_UpdateRefreshToken_Call) RunAndReturn(run func(context.Context, database.UpdateRefreshTokenParams) (database.RefreshToken, error)) *MockQuerierer_UpdateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserDescription provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) UpdateUserDescription(ctx context.Context, arg database.UpdateUserDescriptionParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserDescription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateUserDescriptionParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_UpdateUserDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserDescription'
type MockQuerierer_UpdateUserDescription_Call struct {
	*mock.Call
}

// UpdateUserDescription is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.UpdateUserDescriptionParams
func (_e *MockQuerierer_Expecter) UpdateUserDescription(ctx interface{}, arg interface{}) *MockQuerierer_UpdateUserDescription_Call {
	return &MockQuerierer_UpdateUserDescription_Call{Call: _e.mock.On("UpdateUserDescription", ctx, arg)}
}

func (_c *MockQuerierer_UpdateUserDescription_Call) Run(run func(ctx context.Context, arg database.UpdateUserDescriptionParams)) *MockQuerierer_UpdateUserDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.UpdateUserDescriptionParams))
	})
	return _c
}

func (_c *MockQuerierer_UpdateUserDescription_Call) Return(_a0 error) *MockQuerierer_UpdateUserDescription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_UpdateUserDescription_Call) RunAndReturn(run func(context.Context, database.UpdateUserDescriptionParams) error) *MockQuerierer_UpdateUserDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) UpdateUserPassword(ctx context.Context, arg database.UpdateUserPasswordParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateUserPasswordParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type MockQuerierer_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.UpdateUserPasswordParams
func (_e *MockQuerierer_Expecter) UpdateUserPassword(ctx interface{}, arg interface{}) *MockQuerierer_UpdateUserPassword_Call {
	return &MockQuerierer_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, arg)}
}

func (_c *MockQuerierer_UpdateUserPassword_Call) Run(run func(ctx context.Context, arg database.UpdateUserPasswordParams)) *MockQuerierer_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.UpdateUserPasswordParams))
	})
	return _c
}

func (_c *MockQuerierer_UpdateUserPassword_Call) Return(_a0 error) *MockQuerierer_UpdateUserPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_UpdateUserPassword_Call) RunAndReturn(run func(context.Context, database.UpdateUserPasswordParams) error) *MockQuerierer_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEntry provides a mock function with given fields: ctx, arg
func (_m *MockQuerierer) VerifyEntry(ctx context.Context, arg database.VerifyEntryParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.VerifyEntryParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerierer_VerifyEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEntry'
type MockQuerierer_VerifyEntry_Call struct {
	*mock.Call
}

// VerifyEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.VerifyEntryParams
func (_e *MockQuerierer_Expecter) VerifyEntry(ctx interface{}, arg interface{}) *MockQuerierer_VerifyEntry_Call {
	return &MockQuerierer_VerifyEntry_Call{Call: _e.mock.On("VerifyEntry", ctx, arg)}
}

func (_c *MockQuerierer_VerifyEntry_Call) Run(run func(ctx context.Context, arg database.VerifyEntryParams)) *MockQuerierer_VerifyEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.VerifyEntryParams))
	})
	return _c
}

func (_c *MockQuerierer_VerifyEntry_Call) Return(_a0 error) *MockQuerierer_VerifyEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerierer_VerifyEntry_Call) RunAndReturn(run func(context.Context, database.VerifyEntryParams) error) *MockQuerierer_VerifyEntry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerierer creates a new instance of MockQuerierer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerierer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerierer {
	mock := &MockQuerierer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
